# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: faf3601e66251c09a58efa99882c43932bd9944aa8ce426feedbe19061161f790b7defcac0a37d8f51d8426aa99c4c0fd3449463be1e2fc5c5eb766ffdecf8cc

test:
  secret_key_base: ff5cd8db6bb77adc40e8d58f356c7cc3932c337556f9dca59a555708e2491279719bab2afd6eb6dd8d6141f5892e989b8a681b70c0a78802511d8a369b4f9a7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
